### ISSUE TITLE
Update runkit example of immutadot-lodash

### ISSUE THREAD

**Issue by frinyvonnick** [zenika-open-source/immutadot#335] opened 2019-05-10 13:58 UTC
### Prerequisites
 - [x] I have read the [Contributing guidelines](https://github.com/Zenika/immutadot/blob/master/.github/CONTRIBUTING.md)
 - [x] I have read the [Code of conduct](https://github.com/Zenika/immutadot/blob/master/.github/CODE_OF_CONDUCT.md) and I agree with it

### Description
It misses the orderBy import

**Comment by nlepage** [comment] 2019-06-05 07:58
Duplicate of #226

**Closed by nlepage** 2019-06-05 07:58 UTC
Labels: :baby: New contibutor, :bug: bug
